#Edit default value of kube-prometheus-stack chart that is stored in default value section on "https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack"

#Edit Promethus default value
prometheus:
  service:
    type: NodePort
    nodePort: 30090  

#Edit Grafana default value
grafana:
  adminPassword: "1234"
  service:
    name: service
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 30036
  # To make Grafana persistent (Using Statefulset)
  persistence:
    enabled: true
    type: sts 
    storageClassName: "grafana-storage-class"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
  

